/**
 * Setting up BackEnd Server with OpenAPI implementation
 */

// Importing express dependency similar to import package-name in python
const express = require('express');
require('dotenv').config()

// Allows for Communication between backend and frontend
const cors = require('cors') // Allows you to make requests from one website to another website in browser
const {Configuration, OpenAIApi } = require("openai")

// Creating an config object through a constructor containing a property called apiKey
const configuration = new Configuration({
    apiKey: process.env.OPEN_API_KEY,
});

// Creating an open api object using the configuration
const openai = new OpenAIApi(configuration)

const app = express();
const port = 5000;

app.use(express.json()); // Pass JSON from frontend to backend
app.use(cors());
// Telling Express app to use current directory as our main folder
// app.use(express.static(__dirname));

// Receive data from frontend
// two parameters (path, callback functions)
// we only have one call back function (res.send) and it's a lambda function
app.get('/', function (req, res) {
    res.status(200).send({
        message: 'Hello World!',
    }) 
});

/**
 * Sending Response back to frontend through post function
 * Using openai's createChatCompletion Method to create an openAI completion
 * We need to pass in some inputs such as model and messages
 * 1) model: the type of language model we want to use (gpt-3.5-turbo)
 * 2) messages:
 *    System message: tells the model to act like a certain kind of assistant. So, from now on, it 
 *      will act as an assitant that writes short greeting cards.
 *    User message: User's prompt from the given inputs 
 */
app.post('/', async(req, res) => {
    const violation= "Your inputs have been classified as content that violates OpenAI's usage policies. Please enter \
    new inputs to generate a new message or image."; // Our violation message
    try {
        const message_prompt = req.body.message_prompt; // we will send backend an object with a body with prompt variable
        const image_prompt = req.body.image_prompt; // we will send backend an object with a body with prompt variable
        console.log("How the prompt is defined in backend: " + message_prompt + "\n " + image_prompt);
        const p_messages = [
            {"role": "system", "content": "You will be writing messages based on user needs."},
            {"role": "user", "content": message_prompt}
        ];
        // moderation for given user message
        const message_flag = openai.createModeration({
            input: message_prompt
        });
        if ((await message_flag).data.results[0].flagged === true) {
            // Sending prompt and image violations back to frontend
            res.status(200).send({
                // bot: "Connection successful!"
                bot: violation,
                image_bot: violation
            })
        } else { // create message with ChatGPT because not flagged as harmful content
            const response = await openai.createChatCompletion({
                model: "gpt-3.5-turbo",
                messages: p_messages,
                temperature: 0.1,
            });
            console.log("This is the message from the backend: "+ response.data.choices[0].message.content);
            // Asking ChatGPT for a Dall-E Prompt
            const i_messages = [
                {"role": "system", "content": "You will be generating good DALL-E prompts that will generate images that correspond with the user's prompts."},
                {"role": "user", "content": image_prompt}
            ];
            const dallE_response = await openai.createChatCompletion({
                model: "gpt-3.5-turbo",
                messages: i_messages,
                temperature: 0.1,
            });
            // Grabs the DALL-E prompt generated by ChatGPT
            const dallE_prompt = dallE_response.data.choices[0].message.content;
            console.log(dallE_prompt);
            // moderation for DALL-E Prompt
            const image_flag = openai.createModeration({
                input: dallE_prompt
            });
            if ((await image_flag).data.results[0].flagged === true) {
                res.status(200).send({
                    bot: response.data.choices[0].message.content,
                    image_bot: violation
                })                   
            } else {
                // send the DALL-E Prompt to DALL-E
                const image = await openai.createImage({
                    prompt: dallE_prompt,
                    n: 1,
                    size: "256x256"
                });
                // prints the url of the image
                console.log(image.data.data[0].url);
                res.status(200).send({
                    bot: response.data.choices[0].message.content,
                    image_bot: image.data.data[0].url
                })  
            }
        }
    } catch (error) {
        // if the url has generations, then this is a DALL-E error and we can still send the message
        console.log("This is error: " + error)
        if (error.config.url.includes("generations")) {
            const message_prompt = req.body.message_prompt; // we will send backend an object with a body with prompt variable
            const p_messages = [
                {"role": "system", "content": "You will be writing messages based on user needs."},
                {"role": "user", "content": message_prompt}
            ];
            const response = await openai.createChatCompletion({
                model: "gpt-3.5-turbo",
                messages: p_messages,
                temperature: 0.1,
            });
            res.status(500).send({
                bot: response.data.choices[0].message.content,
                image_bot: violation
            })    
        } else {
            res.status(500).send({
                bot: "ChatGPT may be down or the API Key used has run out of credits. Please contact the staff on the About Section!"
            })
        }
    }
})

// Listens for incoming requests (listen also has a callback function)
app.listen(port, () => {
    console.log(`Now listening on http://localhost:${port}`);
});


